# Generated by Django 5.2 on 2025-04-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datebase_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='passport',
        ),
        migrations.AddField(
            model_name='passport',
            name='passport_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datebase_app.user'),
        ),
    ]
