# Generated by Django 5.2 on 2025-04-23 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='title',
        ),
        migrations.AddField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
