# Generated by Django 5.2 on 2025-05-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('complated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'APIの練習テーブル',
            },
        ),
    ]
