# Generated by Django 5.2 on 2025-04-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('memo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
        ),
    ]
